### ISSUE TITLE
Incompatible, requiring build 213.* or earlier

### ISSUE THREAD

**Issue by Chris-May** [pyvenvmanage/PyVenvManage#13]
Hello maintainers!

I'm excited to see activity on this repo. Thanks for all your work!

PyVenv Manage has not worked in my PyCharm for a while, with the message:

```Incompatible, requiring build 213.* or earlier```

Is there a way to install a working version of the plugin?

If not, I'll be happy to wait for an update patiently.

**Comment by gaborbernat** [comment]
You can install it manually by downloading an updated version from the artifact section here https://github.com/pyvenvmanage/PyVenvManage/actions/runs/3600006961. We're working in publishing it to the marketplace but that might take a few more days.

**Comment by Chris-May** [comment]
That's excellent news. Thank you again for all your work!!!
