### ISSUE TITLE
Setup automatic publishing

### ISSUE THREAD

**Issue by andrask** [pyvenvmanage/PyVenvManage#2]
Hi @gaborbernat, I added a publish token with the name: PUBLISH_TOKEN
I guess we can use a workflow similar to this one https://github.com/JetBrains/intellij-platform-plugin-template/actions/runs/138306507/workflow

However, I had to change the plugin id, so a simple update will probably not be enough. I'll probably have to remove the existing plugin first.

What will be the trigger for the publishing? Can we make it manual?

**Comment by gaborbernat** [comment]
It should be creating a GitHub tag (via cutting a release on the UI e.g., making it too manual would just hinder keeping this plugin up to date).

**Comment by gaborbernat** [comment]
@andrask ping on this

**Comment by andrask** [comment]
I requested the removal of the original plugin. Once it's done in at most a few days, I'll upload the first version of this one. Then the automated publishing can keep pushing the new versions.

**Comment by gaborbernat** [comment]
Thanks for the update!

**Comment by gaborbernat** [comment]
Ping on this 👍

**Comment by gaborbernat** [comment]
@andrask ping on this when you have some time 🙇

**Comment by andrask** [comment]
I had a few days long discussion with JetBrains that ended with archiving the original plugin and me uploading the new version with the name PyvenvManage2. It was not possible to change the plugin id for the existing one.

So we just have to wait until the first version is approved. Then the automation can take care of uploading the new versions.

**Comment by andrask** [comment]
Plugin's first version has been approved and I already tried the cli publishing on the test channel. So we should now figure out how could we trigger the publishing. Simplest would be triggering manually and during the workflow, it would increase the version automatically.

Btw is your JB account the "Bernát_Gábor"?

**Comment by gaborbernat** [comment]
Just changed it to `gaborbernat` 👍

**Comment by gaborbernat** [comment]
> Plugin's first version has been approved and I already tried the cli publishing on the test channel. So we should now figure out how could we trigger the publishing. Simplest would be triggering manually and during the workflow, it would increase the version automatically.

Ideally would be nice to release by cutting a release on the Github UI, but a manual step would be the first acceptable step. Would it be possible to pull the version number from the VCS instead of hardcoding it?

**Comment by gaborbernat** [comment]
@andrask ping on this :blush:

**Comment by andrask** [comment]
I added the secret env var to the workflow and pushed the publish: https://github.com/pyvenvmanage/PyVenvManage/actions/runs/3933457414
I can see the new version in the Jetbrains UI. They will approve it in a day or two and everyone can resume using this magnficient tool. :)
BTW, I invited you to the PyVenvManage Jetbrains org (or at least I hope you are the user with the name "Bernát Gábor") You should also be able to exec admin operations on the plugin.

**Comment by andrask** [comment]
@gaborbernat Celebration! The first auto-published version is now available for download. https://plugins.jetbrains.com/plugin/20536-pyvenv-manage-2
